repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.1
    hooks:
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: detect-aws-credentials
      args: [--allow-missing-credentials]
    - id: detect-private-key
    - id: pretty-format-json
      args: [--autofix]
  - repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
    - id: black
      language_version: python3.6
  - repo: https://github.com/timothycrosley/isort
    rev: develop
    hooks:
    - id: isort
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.1
    hooks:
    - id: flake8